# Generated by Django 5.0.2 on 2024-06-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_type',
            field=models.CharField(choices=[('personal', '个人'), ('group', '团体')], default='personal', max_length=10),
        ),
    ]
