# Generated by Django 5.0.2 on 2024-06-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_reservation_name_reservation_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='group_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_of_people',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
